# environment.yml
name: covid-heterogenous-effect
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scipy
  - statsmodels
  - scikit-learn
  - geopandas        
  - jupyter
  - pip
  - pip:
    - econml         
    - causalml       
    - dowhy 
    - linearmodels         